//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace CyT.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConvocatoriasAbiertasSoap", Namespace="http://cyt.com/")]
    public partial class ConvocatoriasAbiertas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MostrarConvocatoriasAbiertasOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarConvocatoriasPorModalidadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConvocatoriasAbiertas() {
            this.Url = global::CyT.Properties.Settings.Default.CyT_localhost_ConvocatoriasAbiertas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MostrarConvocatoriasAbiertasCompletedEventHandler MostrarConvocatoriasAbiertasCompleted;
        
        /// <remarks/>
        public event MostrarConvocatoriasPorModalidadCompletedEventHandler MostrarConvocatoriasPorModalidadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyt.com/MostrarConvocatoriasAbiertas", RequestNamespace="http://cyt.com/", ResponseNamespace="http://cyt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Convocatorium[] MostrarConvocatoriasAbiertas() {
            object[] results = this.Invoke("MostrarConvocatoriasAbiertas", new object[0]);
            return ((Convocatorium[])(results[0]));
        }
        
        /// <remarks/>
        public void MostrarConvocatoriasAbiertasAsync() {
            this.MostrarConvocatoriasAbiertasAsync(null);
        }
        
        /// <remarks/>
        public void MostrarConvocatoriasAbiertasAsync(object userState) {
            if ((this.MostrarConvocatoriasAbiertasOperationCompleted == null)) {
                this.MostrarConvocatoriasAbiertasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarConvocatoriasAbiertasOperationCompleted);
            }
            this.InvokeAsync("MostrarConvocatoriasAbiertas", new object[0], this.MostrarConvocatoriasAbiertasOperationCompleted, userState);
        }
        
        private void OnMostrarConvocatoriasAbiertasOperationCompleted(object arg) {
            if ((this.MostrarConvocatoriasAbiertasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarConvocatoriasAbiertasCompleted(this, new MostrarConvocatoriasAbiertasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyt.com/MostrarConvocatoriasPorModalidad", RequestNamespace="http://cyt.com/", ResponseNamespace="http://cyt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Convocatorium[] MostrarConvocatoriasPorModalidad(Modalidad modalidad) {
            object[] results = this.Invoke("MostrarConvocatoriasPorModalidad", new object[] {
                        modalidad});
            return ((Convocatorium[])(results[0]));
        }
        
        /// <remarks/>
        public void MostrarConvocatoriasPorModalidadAsync(Modalidad modalidad) {
            this.MostrarConvocatoriasPorModalidadAsync(modalidad, null);
        }
        
        /// <remarks/>
        public void MostrarConvocatoriasPorModalidadAsync(Modalidad modalidad, object userState) {
            if ((this.MostrarConvocatoriasPorModalidadOperationCompleted == null)) {
                this.MostrarConvocatoriasPorModalidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarConvocatoriasPorModalidadOperationCompleted);
            }
            this.InvokeAsync("MostrarConvocatoriasPorModalidad", new object[] {
                        modalidad}, this.MostrarConvocatoriasPorModalidadOperationCompleted, userState);
        }
        
        private void OnMostrarConvocatoriasPorModalidadOperationCompleted(object arg) {
            if ((this.MostrarConvocatoriasPorModalidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarConvocatoriasPorModalidadCompleted(this, new MostrarConvocatoriasPorModalidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cyt.com/")]
    public partial class Convocatorium {
        
        private int idConvocatoriaField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string objetivoField;
        
        private System.Nullable<int> idFondoField;
        
        private System.Nullable<int> anioField;
        
        private System.Nullable<int> idTipoFinanciamientoField;
        
        private System.Nullable<int> idModalidadField;
        
        private System.Nullable<decimal> montoTotalField;
        
        private System.Nullable<decimal> montoProyectoField;
        
        private System.Nullable<System.DateTime> fechaInicioField;
        
        private System.Nullable<System.DateTime> fechaCierreField;
        
        private System.Nullable<int> isAbiertaField;
        
        private System.Nullable<bool> activaField;
        
        private Fondo fondoField;
        
        private Modalidad modalidadField;
        
        private TipoFinanciamiento tipoFinanciamientoField;
        
        /// <remarks/>
        public int IdConvocatoria {
            get {
                return this.idConvocatoriaField;
            }
            set {
                this.idConvocatoriaField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Objetivo {
            get {
                return this.objetivoField;
            }
            set {
                this.objetivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdFondo {
            get {
                return this.idFondoField;
            }
            set {
                this.idFondoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdTipoFinanciamiento {
            get {
                return this.idTipoFinanciamientoField;
            }
            set {
                this.idTipoFinanciamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdModalidad {
            get {
                return this.idModalidadField;
            }
            set {
                this.idModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoProyecto {
            get {
                return this.montoProyectoField;
            }
            set {
                this.montoProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaCierre {
            get {
                return this.fechaCierreField;
            }
            set {
                this.fechaCierreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IsAbierta {
            get {
                return this.isAbiertaField;
            }
            set {
                this.isAbiertaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
            }
        }
        
        /// <remarks/>
        public Fondo Fondo {
            get {
                return this.fondoField;
            }
            set {
                this.fondoField = value;
            }
        }
        
        /// <remarks/>
        public Modalidad Modalidad {
            get {
                return this.modalidadField;
            }
            set {
                this.modalidadField = value;
            }
        }
        
        /// <remarks/>
        public TipoFinanciamiento TipoFinanciamiento {
            get {
                return this.tipoFinanciamientoField;
            }
            set {
                this.tipoFinanciamientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cyt.com/")]
    public partial class Fondo {
        
        private int idFondoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private System.Nullable<int> idOrigenField;
        
        private System.Nullable<bool> activoField;
        
        private Origen origenField;
        
        /// <remarks/>
        public int IdFondo {
            get {
                return this.idFondoField;
            }
            set {
                this.idFondoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdOrigen {
            get {
                return this.idOrigenField;
            }
            set {
                this.idOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        public Origen Origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cyt.com/")]
    public partial class Origen {
        
        private int idOrigenField;
        
        private string nombreField;
        
        /// <remarks/>
        public int IdOrigen {
            get {
                return this.idOrigenField;
            }
            set {
                this.idOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cyt.com/")]
    public partial class TipoFinanciamiento {
        
        private int idTipoFinanciamientoField;
        
        private string nombreField;
        
        /// <remarks/>
        public int IdTipoFinanciamiento {
            get {
                return this.idTipoFinanciamientoField;
            }
            set {
                this.idTipoFinanciamientoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cyt.com/")]
    public partial class Modalidad {
        
        private int idModalidadField;
        
        private string nombreField;
        
        /// <remarks/>
        public int IdModalidad {
            get {
                return this.idModalidadField;
            }
            set {
                this.idModalidadField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MostrarConvocatoriasAbiertasCompletedEventHandler(object sender, MostrarConvocatoriasAbiertasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarConvocatoriasAbiertasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarConvocatoriasAbiertasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Convocatorium[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Convocatorium[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MostrarConvocatoriasPorModalidadCompletedEventHandler(object sender, MostrarConvocatoriasPorModalidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarConvocatoriasPorModalidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarConvocatoriasPorModalidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Convocatorium[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Convocatorium[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591