//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace CyT.AlquileresWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MostrarAlquileresSoap", Namespace="http://alquileres.org/")]
    public partial class MostrarAlquileres : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TodasLasPropiedadesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MostrarAlquileres() {
            this.Url = global::CyT.Properties.Settings.Default.CyT_AlquileresWebService_MostrarAlquileres;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TodasLasPropiedadesCompletedEventHandler TodasLasPropiedadesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alquileres.org/TodasLasPropiedades", RequestNamespace="http://alquileres.org/", ResponseNamespace="http://alquileres.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcedimientoListarPropiedades2ResultSet0[] TodasLasPropiedades() {
            object[] results = this.Invoke("TodasLasPropiedades", new object[0]);
            return ((ProcedimientoListarPropiedades2ResultSet0[])(results[0]));
        }
        
        /// <remarks/>
        public void TodasLasPropiedadesAsync() {
            this.TodasLasPropiedadesAsync(null);
        }
        
        /// <remarks/>
        public void TodasLasPropiedadesAsync(object userState) {
            if ((this.TodasLasPropiedadesOperationCompleted == null)) {
                this.TodasLasPropiedadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodasLasPropiedadesOperationCompleted);
            }
            this.InvokeAsync("TodasLasPropiedades", new object[0], this.TodasLasPropiedadesOperationCompleted, userState);
        }
        
        private void OnTodasLasPropiedadesOperationCompleted(object arg) {
            if ((this.TodasLasPropiedadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodasLasPropiedadesCompleted(this, new TodasLasPropiedadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alquileres.org/")]
    public partial class ProcedimientoListarPropiedades2ResultSet0 {
        
        private string nombreUsuarioField;
        
        private string apellidoField;
        
        private string nombrePropiedadField;
        
        private string nombreBarrioField;
        
        private string emailField;
        
        private System.Nullable<int> bañosField;
        
        private System.Nullable<int> habitacionesField;
        
        private string garageField;
        
        /// <remarks/>
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string NombrePropiedad {
            get {
                return this.nombrePropiedadField;
            }
            set {
                this.nombrePropiedadField = value;
            }
        }
        
        /// <remarks/>
        public string NombreBarrio {
            get {
                return this.nombreBarrioField;
            }
            set {
                this.nombreBarrioField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Baños {
            get {
                return this.bañosField;
            }
            set {
                this.bañosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Habitaciones {
            get {
                return this.habitacionesField;
            }
            set {
                this.habitacionesField = value;
            }
        }
        
        /// <remarks/>
        public string Garage {
            get {
                return this.garageField;
            }
            set {
                this.garageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TodasLasPropiedadesCompletedEventHandler(object sender, TodasLasPropiedadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodasLasPropiedadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodasLasPropiedadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcedimientoListarPropiedades2ResultSet0[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcedimientoListarPropiedades2ResultSet0[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591