#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Convocatorium
	{
		private int idConvocatoria;
		public virtual int IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this.descripcion;
			}
			set
			{
				this.descripcion = value;
			}
		}
		
		private string objetivo;
		public virtual string Objetivo
		{
			get
			{
				return this.objetivo;
			}
			set
			{
				this.objetivo = value;
			}
		}
		
		private int? idFondo;
		public virtual int? IdFondo
		{
			get
			{
				return this.idFondo;
			}
			set
			{
				this.idFondo = value;
			}
		}
		
		private int? anio;
		public virtual int? Anio
		{
			get
			{
				return this.anio;
			}
			set
			{
				this.anio = value;
			}
		}
		
		private int? idTipoFinanciamiento;
		public virtual int? IdTipoFinanciamiento
		{
			get
			{
				return this.idTipoFinanciamiento;
			}
			set
			{
				this.idTipoFinanciamiento = value;
			}
		}
		
		private int? idModalidad;
		public virtual int? IdModalidad
		{
			get
			{
				return this.idModalidad;
			}
			set
			{
				this.idModalidad = value;
			}
		}
		
		private decimal? montoTotal;
		public virtual decimal? MontoTotal
		{
			get
			{
				return this.montoTotal;
			}
			set
			{
				this.montoTotal = value;
			}
		}
		
		private decimal? montoProyecto;
		public virtual decimal? MontoProyecto
		{
			get
			{
				return this.montoProyecto;
			}
			set
			{
				this.montoProyecto = value;
			}
		}
		
		private DateTime? fechaInicio;
		public virtual DateTime? FechaInicio
		{
			get
			{
				return this.fechaInicio;
			}
			set
			{
				this.fechaInicio = value;
			}
		}
		
		private DateTime? fechaCierre;
		public virtual DateTime? FechaCierre
		{
			get
			{
				return this.fechaCierre;
			}
			set
			{
				this.fechaCierre = value;
			}
		}
		
		private int? isAbierta;
		public virtual int? IsAbierta
		{
			get
			{
				return this.isAbierta;
			}
			set
			{
				this.isAbierta = value;
			}
		}
		
		private TipoFinanciamiento tipoFinanciamiento;
		public virtual TipoFinanciamiento TipoFinanciamiento
		{
			get
			{
				return this.tipoFinanciamiento;
			}
			set
			{
				this.tipoFinanciamiento = value;
			}
		}
		
		private Modalidad modalidad;
		public virtual Modalidad Modalidad
		{
			get
			{
				return this.modalidad;
			}
			set
			{
				this.modalidad = value;
			}
		}
		
		private Fondo fondo;
		public virtual Fondo Fondo
		{
			get
			{
				return this.fondo;
			}
			set
			{
				this.fondo = value;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
		private IList<TipoDestinatario> tipoDestinatarios = new List<TipoDestinatario>();
		public virtual IList<TipoDestinatario> TipoDestinatarios
		{
			get
			{
				return this.tipoDestinatarios;
			}
		}
		
	}
}
#pragma warning restore 1591
