#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"Conn";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel1.rlinq");
		
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<ViaComunicacion> ViaComunicacions 
		{
			get
			{
				return this.GetAll<ViaComunicacion>();
			}
		}
		
		public IQueryable<Uvt> Uvts 
		{
			get
			{
				return this.GetAll<Uvt>();
			}
		}
		
		public IQueryable<TipoFinanciamiento> TipoFinanciamientos 
		{
			get
			{
				return this.GetAll<TipoFinanciamiento>();
			}
		}
		
		public IQueryable<TipoDestinatario> TipoDestinatarios 
		{
			get
			{
				return this.GetAll<TipoDestinatario>();
			}
		}
		
		public IQueryable<Tematica> Tematicas 
		{
			get
			{
				return this.GetAll<Tematica>();
			}
		}
		
		public IQueryable<Telefono> Telefonos 
		{
			get
			{
				return this.GetAll<Telefono>();
			}
		}
		
		public IQueryable<Proyecto> Proyectos 
		{
			get
			{
				return this.GetAll<Proyecto>();
			}
		}
		
		public IQueryable<Persona> Personas 
		{
			get
			{
				return this.GetAll<Persona>();
			}
		}
		
		public IQueryable<Origen> Origens 
		{
			get
			{
				return this.GetAll<Origen>();
			}
		}
		
		public IQueryable<Modalidad> Modalidads 
		{
			get
			{
				return this.GetAll<Modalidad>();
			}
		}
		
		public IQueryable<Localidad> Localidads 
		{
			get
			{
				return this.GetAll<Localidad>();
			}
		}
		
		public IQueryable<Fondo> Fondos 
		{
			get
			{
				return this.GetAll<Fondo>();
			}
		}
		
		public IQueryable<Etapa> Etapas 
		{
			get
			{
				return this.GetAll<Etapa>();
			}
		}
		
		public IQueryable<Estado> Estados 
		{
			get
			{
				return this.GetAll<Estado>();
			}
		}
		
		public IQueryable<CorreoElectronico> CorreoElectronicos 
		{
			get
			{
				return this.GetAll<CorreoElectronico>();
			}
		}
		
		public IQueryable<Convocatorium> Convocatoria 
		{
			get
			{
				return this.GetAll<Convocatorium>();
			}
		}
		
		public IQueryable<AreaProductiva> AreaProductivas 
		{
			get
			{
				return this.GetAll<AreaProductiva>();
			}
		}
		
		public IQueryable<Actuacion> Actuacions 
		{
			get
			{
				return this.GetAll<Actuacion>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<ViaComunicacion> ViaComunicacions
		{
			get;
		}
		IQueryable<Uvt> Uvts
		{
			get;
		}
		IQueryable<TipoFinanciamiento> TipoFinanciamientos
		{
			get;
		}
		IQueryable<TipoDestinatario> TipoDestinatarios
		{
			get;
		}
		IQueryable<Tematica> Tematicas
		{
			get;
		}
		IQueryable<Telefono> Telefonos
		{
			get;
		}
		IQueryable<Proyecto> Proyectos
		{
			get;
		}
		IQueryable<Persona> Personas
		{
			get;
		}
		IQueryable<Origen> Origens
		{
			get;
		}
		IQueryable<Modalidad> Modalidads
		{
			get;
		}
		IQueryable<Localidad> Localidads
		{
			get;
		}
		IQueryable<Fondo> Fondos
		{
			get;
		}
		IQueryable<Etapa> Etapas
		{
			get;
		}
		IQueryable<Estado> Estados
		{
			get;
		}
		IQueryable<CorreoElectronico> CorreoElectronicos
		{
			get;
		}
		IQueryable<Convocatorium> Convocatoria
		{
			get;
		}
		IQueryable<AreaProductiva> AreaProductivas
		{
			get;
		}
		IQueryable<Actuacion> Actuacions
		{
			get;
		}
	}
}
namespace CapaDominio	
{
	public partial class ViaComunicacion
	{
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int idViaComunicacion;
		public virtual int IdViaComunicacion
		{
			get
			{
				return this.idViaComunicacion;
			}
			set
			{
				this.idViaComunicacion = value;
			}
		}
		
		private IList<Actuacion> actuacions = new List<Actuacion>();
		public virtual IList<Actuacion> Actuacions
		{
			get
			{
				return this.actuacions;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Uvt
	{
		private int idUvt;
		public virtual int IdUvt
		{
			get
			{
				return this.idUvt;
			}
			set
			{
				this.idUvt = value;
			}
		}
		
		private string nombreUvt;
		public virtual string NombreUvt
		{
			get
			{
				return this.nombreUvt;
			}
			set
			{
				this.nombreUvt = value;
			}
		}
		
		private string direccion;
		public virtual string Direccion
		{
			get
			{
				return this.direccion;
			}
			set
			{
				this.direccion = value;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
		private IList<Persona> personas = new List<Persona>();
		public virtual IList<Persona> Personas
		{
			get
			{
				return this.personas;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class TipoFinanciamiento
	{
		private int idTipoFinanciamiento;
		public virtual int IdTipoFinanciamiento
		{
			get
			{
				return this.idTipoFinanciamiento;
			}
			set
			{
				this.idTipoFinanciamiento = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Convocatorium> convocatoria = new List<Convocatorium>();
		public virtual IList<Convocatorium> Convocatoria
		{
			get
			{
				return this.convocatoria;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class TipoDestinatario
	{
		private int idTipoDestinatario;
		public virtual int IdTipoDestinatario
		{
			get
			{
				return this.idTipoDestinatario;
			}
			set
			{
				this.idTipoDestinatario = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Convocatorium> convocatoria = new List<Convocatorium>();
		public virtual IList<Convocatorium> Convocatoria
		{
			get
			{
				return this.convocatoria;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Tematica
	{
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int idTematica;
		public virtual int IdTematica
		{
			get
			{
				return this.idTematica;
			}
			set
			{
				this.idTematica = value;
			}
		}
		
		private IList<Actuacion> actuacions = new List<Actuacion>();
		public virtual IList<Actuacion> Actuacions
		{
			get
			{
				return this.actuacions;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Telefono
	{
		private int idTelefono;
		public virtual int IdTelefono
		{
			get
			{
				return this.idTelefono;
			}
			set
			{
				this.idTelefono = value;
			}
		}
		
		private int idPersona;
		public virtual int IdPersona
		{
			get
			{
				return this.idPersona;
			}
			set
			{
				this.idPersona = value;
			}
		}
		
		private string telefono1;
		public virtual string Telefono1
		{
			get
			{
				return this.telefono1;
			}
			set
			{
				this.telefono1 = value;
			}
		}
		
		private Persona persona;
		public virtual Persona Persona
		{
			get
			{
				return this.persona;
			}
			set
			{
				this.persona = value;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Proyecto
	{
		private int idProyecto;
		public virtual int IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private string numeroExp;
		public virtual string NumeroExp
		{
			get
			{
				return this.numeroExp;
			}
			set
			{
				this.numeroExp = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int? idConvocatoria;
		public virtual int? IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private int? idUvt;
		public virtual int? IdUvt
		{
			get
			{
				return this.idUvt;
			}
			set
			{
				this.idUvt = value;
			}
		}
		
		private int? idAreaProductiva;
		public virtual int? IdAreaProductiva
		{
			get
			{
				return this.idAreaProductiva;
			}
			set
			{
				this.idAreaProductiva = value;
			}
		}
		
		private int? idEstado;
		public virtual int? IdEstado
		{
			get
			{
				return this.idEstado;
			}
			set
			{
				this.idEstado = value;
			}
		}
		
		private decimal? montoSolicitado;
		public virtual decimal? MontoSolicitado
		{
			get
			{
				return this.montoSolicitado;
			}
			set
			{
				this.montoSolicitado = value;
			}
		}
		
		private decimal? montoContraparte;
		public virtual decimal? MontoContraparte
		{
			get
			{
				return this.montoContraparte;
			}
			set
			{
				this.montoContraparte = value;
			}
		}
		
		private AreaProductiva areaProductiva;
		public virtual AreaProductiva AreaProductiva
		{
			get
			{
				return this.areaProductiva;
			}
			set
			{
				this.areaProductiva = value;
			}
		}
		
		private Convocatorium convocatorium;
		public virtual Convocatorium Convocatorium
		{
			get
			{
				return this.convocatorium;
			}
			set
			{
				this.convocatorium = value;
			}
		}
		
		private Estado estado;
		public virtual Estado Estado
		{
			get
			{
				return this.estado;
			}
			set
			{
				this.estado = value;
			}
		}
		
		private Uvt uvt;
		public virtual Uvt Uvt
		{
			get
			{
				return this.uvt;
			}
			set
			{
				this.uvt = value;
			}
		}
		
		private IList<Etapa> etapas = new List<Etapa>();
		public virtual IList<Etapa> Etapas
		{
			get
			{
				return this.etapas;
			}
		}
		
		private IList<Localidad> localidads = new List<Localidad>();
		public virtual IList<Localidad> Localidads
		{
			get
			{
				return this.localidads;
			}
		}
		
		private IList<Persona> personas = new List<Persona>();
		public virtual IList<Persona> Personas
		{
			get
			{
				return this.personas;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Persona
	{
		private string tipoDocumento;
		public virtual string TipoDocumento
		{
			get
			{
				return this.tipoDocumento;
			}
			set
			{
				this.tipoDocumento = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int? idLocalidad;
		public virtual int? IdLocalidad
		{
			get
			{
				return this.idLocalidad;
			}
			set
			{
				this.idLocalidad = value;
			}
		}
		
		private bool? isInteresado;
		public virtual bool? IsInteresado
		{
			get
			{
				return this.isInteresado;
			}
			set
			{
				this.isInteresado = value;
			}
		}
		
		private bool? isBeneficiario;
		public virtual bool? IsBeneficiario
		{
			get
			{
				return this.isBeneficiario;
			}
			set
			{
				this.isBeneficiario = value;
			}
		}
		
		private int idPersona;
		public virtual int IdPersona
		{
			get
			{
				return this.idPersona;
			}
			set
			{
				this.idPersona = value;
			}
		}
		
		private DateTime? fechaNacimiento;
		public virtual DateTime? FechaNacimiento
		{
			get
			{
				return this.fechaNacimiento;
			}
			set
			{
				this.fechaNacimiento = value;
			}
		}
		
		private string empresa;
		public virtual string Empresa
		{
			get
			{
				return this.empresa;
			}
			set
			{
				this.empresa = value;
			}
		}
		
		private string documento;
		public virtual string Documento
		{
			get
			{
				return this.documento;
			}
			set
			{
				this.documento = value;
			}
		}
		
		private string direccion;
		public virtual string Direccion
		{
			get
			{
				return this.direccion;
			}
			set
			{
				this.direccion = value;
			}
		}
		
		private string cuil;
		public virtual string Cuil
		{
			get
			{
				return this.cuil;
			}
			set
			{
				this.cuil = value;
			}
		}
		
		private string apellido;
		public virtual string Apellido
		{
			get
			{
				return this.apellido;
			}
			set
			{
				this.apellido = value;
			}
		}
		
		private bool? activo;
		public virtual bool? Activo
		{
			get
			{
				return this.activo;
			}
			set
			{
				this.activo = value;
			}
		}
		
		private Localidad localidad;
		public virtual Localidad Localidad
		{
			get
			{
				return this.localidad;
			}
			set
			{
				this.localidad = value;
			}
		}
		
		private IList<Uvt> uvts = new List<Uvt>();
		public virtual IList<Uvt> Uvts
		{
			get
			{
				return this.uvts;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
		private IList<Telefono> telefonos = new List<Telefono>();
		public virtual IList<Telefono> Telefonos
		{
			get
			{
				return this.telefonos;
			}
		}
		
		private IList<CorreoElectronico> correoElectronicos = new List<CorreoElectronico>();
		public virtual IList<CorreoElectronico> CorreoElectronicos
		{
			get
			{
				return this.correoElectronicos;
			}
		}
		
		private IList<Actuacion> actuacions = new List<Actuacion>();
		public virtual IList<Actuacion> Actuacions
		{
			get
			{
				return this.actuacions;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Origen
	{
		private int idOrigen;
		public virtual int IdOrigen
		{
			get
			{
				return this.idOrigen;
			}
			set
			{
				this.idOrigen = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Fondo> fondos = new List<Fondo>();
		public virtual IList<Fondo> Fondos
		{
			get
			{
				return this.fondos;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Modalidad
	{
		private int idModalidad;
		public virtual int IdModalidad
		{
			get
			{
				return this.idModalidad;
			}
			set
			{
				this.idModalidad = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Convocatorium> convocatoria = new List<Convocatorium>();
		public virtual IList<Convocatorium> Convocatoria
		{
			get
			{
				return this.convocatoria;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Localidad
	{
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int idLocalidad;
		public virtual int IdLocalidad
		{
			get
			{
				return this.idLocalidad;
			}
			set
			{
				this.idLocalidad = value;
			}
		}
		
		private int? codigoPostal;
		public virtual int? CodigoPostal
		{
			get
			{
				return this.codigoPostal;
			}
			set
			{
				this.codigoPostal = value;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
		private IList<Persona> personas = new List<Persona>();
		public virtual IList<Persona> Personas
		{
			get
			{
				return this.personas;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Fondo
	{
		private int idFondo;
		public virtual int IdFondo
		{
			get
			{
				return this.idFondo;
			}
			set
			{
				this.idFondo = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this.descripcion;
			}
			set
			{
				this.descripcion = value;
			}
		}
		
		private int? idOrigen;
		public virtual int? IdOrigen
		{
			get
			{
				return this.idOrigen;
			}
			set
			{
				this.idOrigen = value;
			}
		}
		
		private Origen origen;
		public virtual Origen Origen
		{
			get
			{
				return this.origen;
			}
			set
			{
				this.origen = value;
			}
		}
		
		private IList<Convocatorium> convocatoria = new List<Convocatorium>();
		public virtual IList<Convocatorium> Convocatoria
		{
			get
			{
				return this.convocatoria;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Etapa
	{
		private int idEtapa;
		public virtual int IdEtapa
		{
			get
			{
				return this.idEtapa;
			}
			set
			{
				this.idEtapa = value;
			}
		}
		
		private int? idProyecto;
		public virtual int? IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private int? numero;
		public virtual int? Numero
		{
			get
			{
				return this.numero;
			}
			set
			{
				this.numero = value;
			}
		}
		
		private DateTime? fechaInicio;
		public virtual DateTime? FechaInicio
		{
			get
			{
				return this.fechaInicio;
			}
			set
			{
				this.fechaInicio = value;
			}
		}
		
		private DateTime? fechaFin;
		public virtual DateTime? FechaFin
		{
			get
			{
				return this.fechaFin;
			}
			set
			{
				this.fechaFin = value;
			}
		}
		
		private decimal? montoEtapa;
		public virtual decimal? MontoEtapa
		{
			get
			{
				return this.montoEtapa;
			}
			set
			{
				this.montoEtapa = value;
			}
		}
		
		private Proyecto proyecto;
		public virtual Proyecto Proyecto
		{
			get
			{
				return this.proyecto;
			}
			set
			{
				this.proyecto = value;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Estado
	{
		private int idEstado;
		public virtual int IdEstado
		{
			get
			{
				return this.idEstado;
			}
			set
			{
				this.idEstado = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class CorreoElectronico
	{
		private int idCorreoElectronico;
		public virtual int IdCorreoElectronico
		{
			get
			{
				return this.idCorreoElectronico;
			}
			set
			{
				this.idCorreoElectronico = value;
			}
		}
		
		private int idPersona;
		public virtual int IdPersona
		{
			get
			{
				return this.idPersona;
			}
			set
			{
				this.idPersona = value;
			}
		}
		
		private string correoElectronico1;
		public virtual string CorreoElectronico1
		{
			get
			{
				return this.correoElectronico1;
			}
			set
			{
				this.correoElectronico1 = value;
			}
		}
		
		private Persona persona;
		public virtual Persona Persona
		{
			get
			{
				return this.persona;
			}
			set
			{
				this.persona = value;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Convocatorium
	{
		private int idConvocatoria;
		public virtual int IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this.descripcion;
			}
			set
			{
				this.descripcion = value;
			}
		}
		
		private string objetivo;
		public virtual string Objetivo
		{
			get
			{
				return this.objetivo;
			}
			set
			{
				this.objetivo = value;
			}
		}
		
		private int? idFondo;
		public virtual int? IdFondo
		{
			get
			{
				return this.idFondo;
			}
			set
			{
				this.idFondo = value;
			}
		}
		
		private int? anio;
		public virtual int? Anio
		{
			get
			{
				return this.anio;
			}
			set
			{
				this.anio = value;
			}
		}
		
		private int? idTipoFinanciamiento;
		public virtual int? IdTipoFinanciamiento
		{
			get
			{
				return this.idTipoFinanciamiento;
			}
			set
			{
				this.idTipoFinanciamiento = value;
			}
		}
		
		private int? idModalidad;
		public virtual int? IdModalidad
		{
			get
			{
				return this.idModalidad;
			}
			set
			{
				this.idModalidad = value;
			}
		}
		
		private decimal? montoTotal;
		public virtual decimal? MontoTotal
		{
			get
			{
				return this.montoTotal;
			}
			set
			{
				this.montoTotal = value;
			}
		}
		
		private decimal? montoProyecto;
		public virtual decimal? MontoProyecto
		{
			get
			{
				return this.montoProyecto;
			}
			set
			{
				this.montoProyecto = value;
			}
		}
		
		private DateTime? fechaInicio;
		public virtual DateTime? FechaInicio
		{
			get
			{
				return this.fechaInicio;
			}
			set
			{
				this.fechaInicio = value;
			}
		}
		
		private DateTime? fechaCierre;
		public virtual DateTime? FechaCierre
		{
			get
			{
				return this.fechaCierre;
			}
			set
			{
				this.fechaCierre = value;
			}
		}
		
		private int? isAbierta;
		public virtual int? IsAbierta
		{
			get
			{
				return this.isAbierta;
			}
			set
			{
				this.isAbierta = value;
			}
		}
		
		private Fondo fondo;
		public virtual Fondo Fondo
		{
			get
			{
				return this.fondo;
			}
			set
			{
				this.fondo = value;
			}
		}
		
		private Modalidad modalidad;
		public virtual Modalidad Modalidad
		{
			get
			{
				return this.modalidad;
			}
			set
			{
				this.modalidad = value;
			}
		}
		
		private TipoFinanciamiento tipoFinanciamiento;
		public virtual TipoFinanciamiento TipoFinanciamiento
		{
			get
			{
				return this.tipoFinanciamiento;
			}
			set
			{
				this.tipoFinanciamiento = value;
			}
		}
		
		private IList<TipoDestinatario> tipoDestinatarios = new List<TipoDestinatario>();
		public virtual IList<TipoDestinatario> TipoDestinatarios
		{
			get
			{
				return this.tipoDestinatarios;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class AreaProductiva
	{
		private int idAreaProductiva;
		public virtual int IdAreaProductiva
		{
			get
			{
				return this.idAreaProductiva;
			}
			set
			{
				this.idAreaProductiva = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
	}
}
namespace CapaDominio	
{
	public partial class Actuacion
	{
		private int? idViaComunicacion;
		public virtual int? IdViaComunicacion
		{
			get
			{
				return this.idViaComunicacion;
			}
			set
			{
				this.idViaComunicacion = value;
			}
		}
		
		private int? idTematica;
		public virtual int? IdTematica
		{
			get
			{
				return this.idTematica;
			}
			set
			{
				this.idTematica = value;
			}
		}
		
		private int idActuacion;
		public virtual int IdActuacion
		{
			get
			{
				return this.idActuacion;
			}
			set
			{
				this.idActuacion = value;
			}
		}
		
		private DateTime? fecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.fecha;
			}
			set
			{
				this.fecha = value;
			}
		}
		
		private string detalle;
		public virtual string Detalle
		{
			get
			{
				return this.detalle;
			}
			set
			{
				this.detalle = value;
			}
		}
		
		private int? idPersona;
		public virtual int? IdPersona
		{
			get
			{
				return this.idPersona;
			}
			set
			{
				this.idPersona = value;
			}
		}
		
		private Persona persona;
		public virtual Persona Persona
		{
			get
			{
				return this.persona;
			}
			set
			{
				this.persona = value;
			}
		}
		
		private Tematica tematica;
		public virtual Tematica Tematica
		{
			get
			{
				return this.tematica;
			}
			set
			{
				this.tematica = value;
			}
		}
		
		private ViaComunicacion viaComunicacion;
		public virtual ViaComunicacion ViaComunicacion
		{
			get
			{
				return this.viaComunicacion;
			}
			set
			{
				this.viaComunicacion = value;
			}
		}
		
	}
}
#pragma warning restore 1591
