#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class ListaTipoDestinatario
	{
		private int idConvocatoria;
		public virtual int IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private int idTipoDestinatario;
		public virtual int IdTipoDestinatario
		{
			get
			{
				return this.idTipoDestinatario;
			}
			set
			{
				this.idTipoDestinatario = value;
			}
		}
		
		private bool? activo;
		public virtual bool? Activo
		{
			get
			{
				return this.activo;
			}
			set
			{
				this.activo = value;
			}
		}
		
		private Convocatorium convocatorium;
		public virtual Convocatorium Convocatorium
		{
			get
			{
				return this.convocatorium;
			}
			set
			{
				this.convocatorium = value;
			}
		}
		
		private TipoDestinatario tipoDestinatario;
		public virtual TipoDestinatario TipoDestinatario
		{
			get
			{
				return this.tipoDestinatario;
			}
			set
			{
				this.tipoDestinatario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
