#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Persona
	{
		private string tipoDocumento;
		public virtual string TipoDocumento
		{
			get
			{
				return this.tipoDocumento;
			}
			set
			{
				this.tipoDocumento = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int? idLocalidad;
		public virtual int? IdLocalidad
		{
			get
			{
				return this.idLocalidad;
			}
			set
			{
				this.idLocalidad = value;
			}
		}
		
		private bool? isInteresado;
		public virtual bool? IsInteresado
		{
			get
			{
				return this.isInteresado;
			}
			set
			{
				this.isInteresado = value;
			}
		}
		
		private bool? isBeneficiario;
		public virtual bool? IsBeneficiario
		{
			get
			{
				return this.isBeneficiario;
			}
			set
			{
				this.isBeneficiario = value;
			}
		}
		
		private int idPersona;
		public virtual int IdPersona
		{
			get
			{
				return this.idPersona;
			}
			set
			{
				this.idPersona = value;
			}
		}
		
		private DateTime? fechaNacimiento;
		public virtual DateTime? FechaNacimiento
		{
			get
			{
				return this.fechaNacimiento;
			}
			set
			{
				this.fechaNacimiento = value;
			}
		}
		
		private string empresa;
		public virtual string Empresa
		{
			get
			{
				return this.empresa;
			}
			set
			{
				this.empresa = value;
			}
		}
		
		private string documento;
		public virtual string Documento
		{
			get
			{
				return this.documento;
			}
			set
			{
				this.documento = value;
			}
		}
		
		private string direccion;
		public virtual string Direccion
		{
			get
			{
				return this.direccion;
			}
			set
			{
				this.direccion = value;
			}
		}
		
		private string cuil;
		public virtual string Cuil
		{
			get
			{
				return this.cuil;
			}
			set
			{
				this.cuil = value;
			}
		}
		
		private string apellido;
		public virtual string Apellido
		{
			get
			{
				return this.apellido;
			}
			set
			{
				this.apellido = value;
			}
		}
		
		private bool? activo;
		public virtual bool? Activo
		{
			get
			{
				return this.activo;
			}
			set
			{
				this.activo = value;
			}
		}
		
		private Localidad localidad;
		public virtual Localidad Localidad
		{
			get
			{
				return this.localidad;
			}
			set
			{
				this.localidad = value;
			}
		}
		
		private IList<UvtReferente> uvtReferentes = new List<UvtReferente>();
		public virtual IList<UvtReferente> UvtReferentes
		{
			get
			{
				return this.uvtReferentes;
			}
		}
		
		private IList<Telefono> telefonos = new List<Telefono>();
		public virtual IList<Telefono> Telefonos
		{
			get
			{
				return this.telefonos;
			}
		}
		
		private IList<Integrante> integrantes = new List<Integrante>();
		public virtual IList<Integrante> Integrantes
		{
			get
			{
				return this.integrantes;
			}
		}
		
		private IList<CorreoElectronico> correoElectronicos = new List<CorreoElectronico>();
		public virtual IList<CorreoElectronico> CorreoElectronicos
		{
			get
			{
				return this.correoElectronicos;
			}
		}
		
		private IList<Actuacion> actuacions = new List<Actuacion>();
		public virtual IList<Actuacion> Actuacions
		{
			get
			{
				return this.actuacions;
			}
		}
		
	}
}
#pragma warning restore 1591
