#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Proyecto
	{
		private int idProyecto;
		public virtual int IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private string numeroExp;
		public virtual string NumeroExp
		{
			get
			{
				return this.numeroExp;
			}
			set
			{
				this.numeroExp = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int? idConvocatoria;
		public virtual int? IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private int? idUvt;
		public virtual int? IdUvt
		{
			get
			{
				return this.idUvt;
			}
			set
			{
				this.idUvt = value;
			}
		}
		
		private int? idAreaProductiva;
		public virtual int? IdAreaProductiva
		{
			get
			{
				return this.idAreaProductiva;
			}
			set
			{
				this.idAreaProductiva = value;
			}
		}
		
		private int? idEstado;
		public virtual int? IdEstado
		{
			get
			{
				return this.idEstado;
			}
			set
			{
				this.idEstado = value;
			}
		}
		
		private decimal? montoSolicitado;
		public virtual decimal? MontoSolicitado
		{
			get
			{
				return this.montoSolicitado;
			}
			set
			{
				this.montoSolicitado = value;
			}
		}
		
		private decimal? montoContraparte;
		public virtual decimal? MontoContraparte
		{
			get
			{
				return this.montoContraparte;
			}
			set
			{
				this.montoContraparte = value;
			}
		}
		
		private Uvt uvt;
		public virtual Uvt Uvt
		{
			get
			{
				return this.uvt;
			}
			set
			{
				this.uvt = value;
			}
		}
		
		private Estado estado;
		public virtual Estado Estado
		{
			get
			{
				return this.estado;
			}
			set
			{
				this.estado = value;
			}
		}
		
		private Convocatorium convocatorium;
		public virtual Convocatorium Convocatorium
		{
			get
			{
				return this.convocatorium;
			}
			set
			{
				this.convocatorium = value;
			}
		}
		
		private AreaProductiva areaProductiva;
		public virtual AreaProductiva AreaProductiva
		{
			get
			{
				return this.areaProductiva;
			}
			set
			{
				this.areaProductiva = value;
			}
		}
		
		private IList<Localidad> localidads = new List<Localidad>();
		public virtual IList<Localidad> Localidads
		{
			get
			{
				return this.localidads;
			}
		}
		
		private IList<Persona> personas = new List<Persona>();
		public virtual IList<Persona> Personas
		{
			get
			{
				return this.personas;
			}
		}
		
		private IList<Etapa> etapas = new List<Etapa>();
		public virtual IList<Etapa> Etapas
		{
			get
			{
				return this.etapas;
			}
		}
		
	}
}
#pragma warning restore 1591
