#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Proyecto
	{
		private int idProyecto;
		public virtual int IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private string numeroExpediente;
		public virtual string NumeroExpediente
		{
			get
			{
				return this.numeroExpediente;
			}
			set
			{
				this.numeroExpediente = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private float? montoSolicitado;
		public virtual float? MontoSolicitado
		{
			get
			{
				return this.montoSolicitado;
			}
			set
			{
				this.montoSolicitado = value;
			}
		}
		
		private float? montoContraparte;
		public virtual float? MontoContraparte
		{
			get
			{
				return this.montoContraparte;
			}
			set
			{
				this.montoContraparte = value;
			}
		}
		
		private int? idUvt;
		public virtual int? IdUvt
		{
			get
			{
				return this.idUvt;
			}
			set
			{
				this.idUvt = value;
			}
		}
		
		private int? idConvocatoria;
		public virtual int? IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private int? idEstado;
		public virtual int? IdEstado
		{
			get
			{
				return this.idEstado;
			}
			set
			{
				this.idEstado = value;
			}
		}
		
		private Uvt uvt;
		public virtual Uvt Uvt
		{
			get
			{
				return this.uvt;
			}
			set
			{
				this.uvt = value;
			}
		}
		
		private Estado estado;
		public virtual Estado Estado
		{
			get
			{
				return this.estado;
			}
			set
			{
				this.estado = value;
			}
		}
		
		private IList<AreaProductiva> areaProductivas = new List<AreaProductiva>();
		public virtual IList<AreaProductiva> AreaProductivas
		{
			get
			{
				return this.areaProductivas;
			}
		}
		
	}
}
#pragma warning restore 1591
